### PR TITLE
WIP: Tabcordion style fixes

### PR DESCRIPTION
**Pull request by jonnystening**

### CODE REVIEW

**Comment by jonnystening** [comment]
[Default Tabs](https://trello.com/c/T8VD1HzI/301-default-tabs)

**Comment by jonnystening** [comment]
[Lego accordion](https://trello.com/c/PPta34r0/300-lego-accordion)

**Comment by jonnystening** [comment]
[Lego accordion](https://trello.com/c/oLL0nwIP/299-ta)

**Comment by jonnystening** [comment]
[Tabs and Tabcordians](https://trello.com/c/sOlzUfSK/298-tabs-and-tabcordians)

**Comment by jaortiz** [comment]
Do the styling updates work properly with the blender?

**Pull request closed without merging**
