### PR TITLE
Heading size array value fix and changeset

### PR DESCRIPTION
**Pull request by jonnystening**

### CODE REVIEW

**Comment by jonnystening** [comment]
Hey @dominikwilkowski I've updated Heading version from `beta.2` to `beta.3`. Is it correct that the other packages still refer to `@westpac/heading: ^1.0.0-beta.2`?

**Comment by dominikwilkowski** [comment]
What does manypkg say @jonnystening ?

**Comment by dominikwilkowski** [comment]
BTW there is no changeset in this PR

**Comment by jonnystening** [comment]
> What does manypkg say @jonnystening ?

it had no issues

**Comment by jonnystening** [comment]
> BTW there is no changeset in this PR

we ran `yarn changeset version` because the bot didn't run 🤷‍♂️

**Pull request merged**
