### PR TITLE
Refactor getLabel to use switch() instead of chain of if…else

### PR DESCRIPTION
**Pull request by wojtekmaj**
Allows for better optimization on browser engine side as well as improves code clarity

### CODE REVIEW

**Review by jonnystening — APPROVED** [review]
LGTM

**Comment by dominikwilkowski** [comment]
Make sure you add a changeset please and on a personal note: I don't like `switch` statements since they are all too easy to miss a `break` somewhere. But not a strong opinion

**Comment by wojtekmaj** [comment]
@jonnystening Uh, oh. Looks like you didn't update your develop branch from with master branch. I can to rebase this PR if you need!

Note: Set `develop` to your default branch in GitHub settings for PRs to be directed to `develop` by default.

**Comment by wojtekmaj** [comment]
@dominikwilkowski https://eslint.org/docs/rules/no-fallthrough could make you like the switch again :) I can add it to the rules if you think that's a valuable contribution.

**Comment by dominikwilkowski** [comment]
nah all good. No need to add eslint rules just for me ;)

**Comment by jonnystening** [comment]
@wojtekmaj 

> How do I do that? I can't quite wrap my head around naming like poor-dragons-sparkle.md and three-onions-lie.md 😂

The .changeset/*.md filenames are meaningless, just randomly generated to ensure they're unique. They're automatically picked up by https://github.com/WestpacGEL/GEL/pull/750, changeset details added to the appropriate component's CHANGELOG.md file when merged. https://github.com/atlassian/changesets. 

I'm happy to do this one, no probs 👍

**Pull request merged**
